-- GENERATED by `cargo xtask compat-generate` from clients/nvim/compat.json.
-- Do not edit; `cargo xtask compat-check` fails on a hand edit.
--
-- The range of `wolf` this plugin CLAIMS, as opposed to `pin.lua`, which is the
-- single build it was verified against. Pre-1.0 the two are the same width and
-- the docs say so (docs/COMPAT.md): until wolf v1 this is a PIN RANGE, and
-- breakage between compiler campaigns is expected rather than surprising.
--
-- `:checkhealth wolf` reads this. It reports a mismatch and never blocks: an
-- out-of-range server usually mostly works, and refusing to attach would be a
-- worse outcome than a warning nobody had to read twice.
return {
  client = "wolf.nvim",
  client_version = "0.0.1",
  min = "0.2.3",
  max_tested = "0.2.3",
  verified = "2026-09-02",
}
