-- GENERATED by `cargo xtask nvim-generate` from vendor/upstream/PIN.
-- Do not edit; `cargo xtask nvim-check` fails on a hand edit.
--
-- The wolf-lang build this plugin was verified against. `:checkhealth wolf`
-- compares a user's `wolf --version` against `version` and reports a mismatch
-- WITHOUT calling it unsupported: a supported version RANGE is ls07's to
-- define, and this repo's only honest fact today is one exact pin.
return {
  commit = "70bdd35c9d24c5bfba2c46e6334f886d8b2fe474",
  version = "wolf 0.0.1 (pre-alpha)",
  serves_lsp = true,
}
