-- GENERATED by `cargo xtask nvim-generate` from vendor/upstream/PIN.
-- Do not edit; `cargo xtask nvim-check` fails on a hand edit.
--
-- The wolf-lang build this plugin was verified against. `:checkhealth wolf`
-- compares a user's `wolf --version` against `version` and reports a mismatch
-- WITHOUT calling it unsupported: a supported version RANGE is ls07's to
-- define, and this repo's only honest fact today is one exact pin.
return {
  commit = "c2401f05f37794a078d2acf62f837dad98e5950d",
  version = "wolf 0.2.19 (wolfgang, pin c2401f0)",
  serves_lsp = true,
}
