-- GENERATED by `cargo xtask nvim-generate` from vendor/upstream/PIN.
-- Do not edit; `cargo xtask nvim-check` fails on a hand edit.
--
-- The wolf-lang build this plugin was verified against. `:checkhealth wolf`
-- compares a user's `wolf --version` against `version` and reports a mismatch
-- WITHOUT calling it unsupported: a supported version RANGE is ls07's to
-- define, and this repo's only honest fact today is one exact pin.
return {
  commit = "83f83bbf44ce5dd6a8f6e2fe255fa37d1fe3954b",
  version = "wolf 0.2.0+dev.83f83bb (wolfgang, pin 83f83bb)",
  serves_lsp = true,
}
