-- Filetype detection for the wolf toolchain's four file kinds.
--
-- This lives in `ftdetect/` rather than `plugin/` for one concrete reason:
-- lazy.nvim sources a plugin's `ftdetect/` files EAGERLY even when the plugin
-- itself is lazy-loaded on `ft = 'wolf'`. Registering the extension from
-- `plugin/` instead would make that lazy spec a deadlock — the filetype never
-- fires, so the plugin never loads, so the filetype is never registered.
--
-- Extension and filename only. No content sniffing: `.lu` is unclaimed by any
-- other language Neovim knows, so there is nothing to disambiguate, and a
-- filetype plugin that reads the first lines of every file it might own is how
-- `:e` gets slow.

vim.filetype.add({
  extension = {
    -- Programs. `.lu` for lupus.
    lu = 'wolf',
    -- Interface files: generated by the compiler, read far more often than
    -- written. A separate filetype so a user can make them look read-only
    -- without also restyling their source, and so `vim.lsp.enable('wolf')`
    -- does not attach a server to a file it does not serve.
    wolfi = 'wolfi',
  },
  filename = {
    -- Manifests. These are wolf-literal DATA, not programs: highlighting them
    -- as `wolf` would paint a manifest with a program's keyword set and invite
    -- the LSP client to attach to a file the server does not parse.
    ['wolf.pkg'] = 'wolfpkg',
    -- The lockfile. Machine-written; its own filetype so nobody's `wolfpkg`
    -- ftplugin starts editing generated content.
    ['wolf.sum'] = 'wolfsum',
  },
})
