// GENERATED by `cargo xtask compat-generate` from clients/vscode/compat.json.
// Do not edit; `cargo xtask compat-check` fails on a hand edit.
//
// The range of `wolf` this extension CLAIMS, as opposed to `pin.ts`, which is
// the single build it was verified against. Pre-1.0 the two are the same width
// and the docs say so (docs/COMPAT.md): until wolf v1 this is a PIN RANGE, and
// breakage between compiler campaigns is expected rather than surprising.
//
// `activate()` reads this and shows AT MOST ONE notification per session on a
// mismatch. No modal, no repetition, no auto-update, and no refusal to start.

export const COMPAT = {
	client: 'wolf (VS Code extension)',
	clientVersion: '0.0.1',
	min: '0.2.3',
	maxTested: '0.2.3',
	verified: '2026-09-02',
} as const;
