// GENERATED by `cargo xtask grammar-generate` from vendor/upstream/PIN.
// Do not edit; `cargo xtask grammar-drift` fails on a hand edit.
//
// The wolf-lang build this extension was verified against. `Wolf: Show Version`
// compares a user's `wolf --version` against `version` and reports a mismatch
// WITHOUT calling it unsupported: a supported version RANGE is ls07's to
// define, and this repo's only honest fact today is one exact pin.

export const PIN = {
	commit: '70bdd35c9d24c5bfba2c46e6334f886d8b2fe474',
	version: 'wolf 0.0.1 (pre-alpha)',
	servesLsp: true,
} as const;
