// GENERATED by `cargo xtask grammar-generate` from vendor/upstream/PIN.
// Do not edit; `cargo xtask grammar-drift` fails on a hand edit.
//
// The wolf-lang build this extension was verified against. `Wolf: Show Version`
// compares a user's `wolf --version` against `version` and reports a mismatch
// WITHOUT calling it unsupported: a supported version RANGE is ls07's to
// define, and this repo's only honest fact today is one exact pin.

export const PIN = {
	commit: 'c2401f05f37794a078d2acf62f837dad98e5950d',
	version: 'wolf 0.2.19 (wolfgang, pin c2401f0)',
	servesLsp: true,
} as const;
