// GENERATED by `cargo xtask grammar-generate` from vendor/upstream/PIN.
// Do not edit; `cargo xtask grammar-drift` fails on a hand edit.
//
// The wolf-lang build this extension was verified against. `Wolf: Show Version`
// compares a user's `wolf --version` against `version` and reports a mismatch
// WITHOUT calling it unsupported: a supported version RANGE is ls07's to
// define, and this repo's only honest fact today is one exact pin.

export const PIN = {
	commit: '982f857885b991e686c6b045de213d10cab013c1',
	version: 'wolf 0.2.4 (wolfgang, pin 982f857)',
	servesLsp: true,
} as const;
