//! **The VS Code extension's derived artifacts** (ls05 §2).
//!
//! Four files under `clients/vscode/` are *read off* the pin rather than
//! authored, and `grammar-drift` regenerates all four in memory and
//! byte-compares them against what is committed:
//!
//! 1. `syntaxes/wolf.tmLanguage.json` — the TextMate grammar.
//! 2. `syntaxes/wolfi.tmLanguage.json` — `.wolfi`, which is `source.wolf`.
//! 3. `syntaxes/wolf-pkg.tmLanguage.json` — `wolf.pkg`/`wolf.sum`, likewise.
//! 4. `src/pin.ts` — the `wolf` build the extension was verified against, the
//!    same generated constant `clients/nvim/lua/wolf/pin.lua` is.
//!
//! **Why the check is on generated bytes rather than on a keyword list.** ls04
//! compares `syntax/wolf.vim`'s `syn keyword` lines against `reserved_kw` and
//! lets a human write the file. That works for a `.vim` file a human can read
//! at a glance. A `.tmLanguage.json` is 200 lines of escaped regex, and a
//! hand-edit in the middle of it is invisible to any check that only looks at
//! the terminal lists. Generating the whole document and diffing the bytes
//! makes a hand-edit *be* the drift — which is the property ls05 §2 asks for in
//! those words ("the check is on the *generated* content precisely so that
//! hand-edits are visible as drift").
//!
//! # What is derived, and what is not
//!
//! Derived from `vendor/upstream/spec/grammar.ebnf`:
//!
//! - the **keyword set**, from `reserved_kw` — the same 50 names, read by the
//!   same [`crate::reserved_keywords`] the Neovim check uses, so the two
//!   clients cannot disagree about what a keyword is;
//! - the **operator inventory**, from every quoted terminal in the file that is
//!   neither a keyword nor a delimiter.
//!
//! Hand-written here, because the EBNF cannot supply it: the scope *structure*
//! — comment forms, the four string forms and their ordering, `{}`
//! interpolation as an embedded expression scope, `#[…]` as a bounded region,
//! and the number patterns. This is ls05 §2's split, and [`TYPE_NAMES`] is the
//! one place it leaks (see its own comment).
//!
//! # THE OPERATOR GAP — closed at pin f9ee9aa
//!
//! Through the 70bdd35 pin, `wolf xtask spec-extract` **elided the precedence
//! climb**, so the derived inventory was missing `==` `!=` `<` `>` `<=` `>=`
//! `<=>` `&&` `||` `<<` `>>` `/` `&` — thirteen operators that lived only in
//! the un-vendored `spec/01-grammar.md` §3.2, and therefore did not highlight
//! (`==` rendered as two `=`). ls02/ls04 recorded the gap; the remedy was
//! always upstream, and upstream took it: the f9ee9aa EBNF renders the full
//! climb (tiers 3–13) into the extracted grammar, the thirteen are ordinary
//! quoted terminals now, and
//! `the_precedence_climb_operators_stay_in_the_vendored_ebnf` keeps them from
//! silently vanishing again. History: `clients/vscode/inventory.md`.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use serde_json::{Value, json};

/// Word terminals the EBNF carries that are **not** reserved keywords.
///
/// Each is an ordinary identifier everywhere except one position
/// (`[gram.inv.ctx]`), so none of them is highlighted: painting `from` and
/// `timeout` as keywords would be wrong far more often than right, and `self`
/// — the one that tempts hardest — is a field name, a parameter and a local in
/// three other places.
///
/// `E`, `e` and `_` are here for a different reason: they are fragments of the
/// number and pattern grammars (`EXPONENT`, `closed_pattern`), matched by the
/// hand-written numeric rules rather than as words. `n`, `r` and `t` joined
/// them at the 83f83bb pin: they are the escape letters of `CHAR_ESC`
/// (`[gram.lex.char]`, D58), matched inside the hand-written char-literal
/// rule, and colouring the letter `n` as a keyword would be wrong everywhere
/// outside `'\n'`.
///
/// This list is **exhaustive over the pin**, and generation fails when a word
/// terminal appears in neither it nor `reserved_kw`. That failure is the point:
/// a contextual keyword added upstream (`sync`, say) forces a human decision
/// about whether it is contextual or reserved, instead of silently becoming
/// neither.
const CONTEXTUAL: &[&str] = &[
    "E", "_", "c", "e", "from", "inout", "lateout", "n", "noalias", "out", "pkg", "pool", "r",
    "rc", "self", "t", "timeout",
];

/// Symbolic terminals that are **delimiters or literal-form fragments**, not
/// operators.
///
/// The partition is hand-drawn and this is the whole of it: everything
/// symbolic that is not listed here becomes an operator. So a symbol added
/// upstream highlights immediately (and shows up as drift), which is the right
/// default — an uncoloured new operator is a smaller wrong than a silent one.
const DELIMITERS: &[&str] = &[
    "\"", "#![", "#[", "(", ")", ",", ".", ":", "[", "]", "{", "}", // punctuation
    "{{", "}}", // the f-string brace escapes, matched inside strings
    "0b", "0o", "0x", // integer radix prefixes, matched by the numeric rules
    // char-literal fragments ([gram.lex.char], the 83f83bb pin): the quote,
    // the backslash and the `\x`/`\u{` escape openers, and the bare `0` of
    // `'\0'` — matched inside the hand-written char rule, never operators.
    "'", "0", "\\", "\\u{", "\\x",
];

/// The type names the grammar paints, and the one thing in this file that the
/// drift check does **not** cover.
///
/// Wolf's fixed-width scalar inventory is REAL at this pin: spec/10 (types,
/// D54) writes `f32`/`f64`/`i32`/`u8` normatively, and the compiler's closed
/// `BUILTIN_TYPES` set at 83f83bb is the fifteen scalars, `char` (s121, D58
/// — `[type.char]` made it a builtin at this pin) and the `wrapping`
/// constructor (D56) painted here, with `Self` beside them. (Through the
/// 70bdd35 pin this list was four names, because no `spec/*.md` then named a
/// fixed-width scalar and inventing them would have taught users a language
/// that did not exist.) Still *not* re-derivable from the vendored EBNF,
/// which has no rule listing type names — a type added upstream will not
/// appear here on its own; re-read `wolf_sema/src/prelude.rs` at each pin.
/// `type` and `region` are type-level too, but they are reserved keywords and
/// are already coloured as such.
const TYPE_NAMES: &[&str] = &[
    "Self", "bool", "byte", "char", "f32", "f64", "i16", "i32", "i64", "i8", "int", "str", "u16",
    "u32", "u64", "u8", "uint", "wrapping",
];

/// Which scope each reserved keyword is painted with.
///
/// **The split is cosmetic and the union is the claim** — the same sentence
/// `clients/nvim/inventory.md` makes about its seven `syn keyword` groups.
/// Moving a keyword between scopes changes the colour a theme picks and
/// nothing else; what matters is that every name in `reserved_kw` appears
/// exactly once across all of them, which is a property of the generator
/// rather than of anyone's discipline: the lists below are *filtered* by the
/// derived set, and any keyword this table forgets lands in
/// `keyword.other.wolf` rather than vanishing.
const KEYWORD_SCOPES: &[(&str, &[&str])] = &[
    ("constant.language.wolf", &["false", "true"]),
    ("keyword.control.conditional.wolf", &["else", "if", "match"]),
    (
        "keyword.control.repeat.wolf",
        &["for", "in", "loop", "while"],
    ),
    (
        "keyword.control.flow.wolf",
        &["break", "continue", "defer", "errdefer", "return"],
    ),
    ("keyword.control.import.wolf", &["import", "use"]),
    (
        "keyword.control.concurrency.wolf",
        &[
            "borrow", "freeze", "move", "proc", "region", "scope", "select", "spawn", "when",
        ],
    ),
    (
        "storage.type.wolf",
        &[
            "const", "enum", "fn", "impl", "let", "struct", "trait", "type", "var",
        ],
    ),
    (
        "storage.modifier.wolf",
        &[
            "asm", "assume", "comptime", "copy", "distinct", "dyn", "export", "extern", "handle",
            "mut", "pub", "shared", "take", "unsafe", "weak",
        ],
    ),
    // `as` is a cast and a `use`-rename, and belongs to neither family above.
    // Naming it here rather than letting it fall through to the leftover
    // bucket keeps that bucket meaning exactly one thing: a keyword upstream
    // added that nobody has classified yet.
    ("keyword.other.wolf", &["as"]),
];

/// The terminal inventory, read off the pinned EBNF.
pub struct Inventory {
    /// `reserved_kw`, verbatim.
    pub keywords: BTreeSet<String>,
    /// Operator terminals, **longest first** — a TextMate alternation is
    /// first-match, not longest-match, so `..` listed before `..=` would
    /// colour `..=` as a range followed by a stray `=`.
    pub operators: Vec<String>,
}

/// Every `'…'` terminal in the file, with comments removed first.
///
/// **The comment strip is load-bearing, not tidiness.** `grammar.ebnf` mixes
/// prose comments with quoted terminals, and prose contains apostrophes: line
/// 34 is `/* \`-> !T\` parses via type's '!' type */`. Pairing quotes across
/// that line yields the "terminals" `s ` and ` type */`, and a generator that
/// swallowed those would emit them into a user's editor. Stripping `/* … */`
/// (which may span lines) and the `#` header first leaves a file in which every
/// apostrophe is a terminal delimiter — verified by the fact that the word
/// terminals then partition exactly into `reserved_kw` and [`CONTEXTUAL`].
fn terminals(ebnf: &str) -> BTreeSet<String> {
    let mut stripped = String::with_capacity(ebnf.len());
    let mut rest = ebnf;
    while let Some(open) = rest.find("/*") {
        stripped.push_str(&rest[..open]);
        stripped.push(' ');
        match rest[open..].find("*/") {
            Some(close) => rest = &rest[open + close + 2..],
            None => {
                rest = "";
                break;
            }
        }
    }
    stripped.push_str(rest);

    let mut out = BTreeSet::new();
    for line in stripped.lines() {
        if line.starts_with('#') {
            continue;
        }
        // Line-scoped, so an unbalanced quote can never run away past the end
        // of its own line.
        for token in crate::quoted(line) {
            out.insert(token);
        }
    }
    out
}

/// Derive the inventory, or say exactly what is unclassified.
pub fn inventory(ebnf: &str) -> Result<Inventory, Vec<String>> {
    let mut errors = Vec::new();
    let keywords = crate::reserved_keywords(ebnf);
    if keywords.is_empty() {
        errors.push(
            "no `reserved_kw ::=` rule found in vendor/upstream/spec/grammar.ebnf \
             — the extraction this generator depends on has changed shape"
                .to_string(),
        );
        return Err(errors);
    }

    let mut operators: Vec<String> = Vec::new();
    for term in terminals(ebnf) {
        let word = term.starts_with(|c: char| c.is_alphabetic() || c == '_');
        if word {
            if !keywords.contains(&term) && !CONTEXTUAL.contains(&term.as_str()) {
                errors.push(format!(
                    "the pinned grammar carries the word terminal `{term}`, which is neither in \
                     `reserved_kw` nor in xtask's CONTEXTUAL list. Classify it: a reserved \
                     keyword is coloured, a contextual one is deliberately not \
                     (`[gram.inv.ctx]`). Leaving it unclassified would make it neither."
                ));
            }
        } else if !DELIMITERS.contains(&term.as_str()) {
            operators.push(term);
        }
    }

    // Longest first, then lexicographic — a total order, so the emitted
    // alternation is byte-stable across platforms and runs.
    operators.sort_by(|a, b| b.chars().count().cmp(&a.chars().count()).then(a.cmp(b)));

    if errors.is_empty() {
        Ok(Inventory {
            keywords,
            operators,
        })
    } else {
        Err(errors)
    }
}

// ------------------------------------------------------------- emission --

/// Escape a terminal for use inside a TextMate (Oniguruma) pattern.
fn escape(token: &str) -> String {
    let mut out = String::new();
    for c in token.chars() {
        if "\\^$.|?*+()[]{}/".contains(c) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

/// `\b(a|b|c)\b` over a sorted word list.
fn word_alternation(words: &[String]) -> String {
    format!(
        "\\b({})\\b",
        words
            .iter()
            .map(String::as_str)
            .collect::<Vec<_>>()
            .join("|")
    )
}

fn generated_banner(what: &str) -> Value {
    json!([
        "GENERATED by `cargo xtask grammar-generate` from vendor/upstream/spec/grammar.ebnf.",
        "DO NOT EDIT. `cargo xtask grammar-drift` regenerates this file and compares bytes,",
        "so a hand edit here fails CI as drift — which is the point (ls05 §2).",
        format!("This file: {what}"),
        "The remedy for a real upstream change is always one commit: bump the pin,",
        "re-vendor, `cargo xtask grammar-generate`, commit together.",
    ])
}

/// The TextMate grammar for `source.wolf`.
fn wolf_grammar(inv: &Inventory) -> Value {
    // Keyword scopes, each filtered by the DERIVED set so a name this table
    // knows but the pin dropped cannot survive here.
    let mut keyword_patterns: Vec<Value> = Vec::new();
    let mut placed: BTreeSet<String> = BTreeSet::new();
    for (scope, names) in KEYWORD_SCOPES {
        let words: Vec<String> = names
            .iter()
            .filter(|n| inv.keywords.contains(**n))
            .map(|n| (*n).to_string())
            .collect();
        for w in &words {
            placed.insert(w.clone());
        }
        if words.is_empty() {
            continue;
        }
        keyword_patterns.push(json!({ "name": scope, "match": word_alternation(&words) }));
    }
    // Anything `reserved_kw` carries that KEYWORD_SCOPES forgot still reaches
    // the user's editor, in the generic scope, and still shows as drift.
    let leftover: Vec<String> = inv.keywords.difference(&placed).cloned().collect();
    if !leftover.is_empty() {
        keyword_patterns.push(json!({
            "name": "keyword.other.wolf",
            "match": word_alternation(&leftover),
        }));
    }

    let operator_alternation = inv
        .operators
        .iter()
        .map(|o| escape(o))
        .collect::<Vec<_>>()
        .join("|");

    let types: Vec<String> = TYPE_NAMES.iter().map(|s| (*s).to_string()).collect();

    json!({
        "information_for_contributors": generated_banner("the TextMate grammar for `.lu` source."),
        "name": "Wolf",
        "scopeName": "source.wolf",
        "patterns": [
            { "include": "#comments" },
            { "include": "#attributes" },
            { "include": "#strings" },
            { "include": "#chars" },
            { "include": "#numbers" },
            { "include": "#keywords" },
            { "include": "#types" },
            { "include": "#operators" }
        ],
        "repository": {
            // Doc comments FIRST: the earliest-listed rule wins, and `//`
            // would otherwise swallow `///` and `//!`.
            "comments": {
                "patterns": [
                    {
                        "name": "comment.line.documentation.wolf",
                        "match": "//[/!].*$"
                    },
                    {
                        "name": "comment.line.double-slash.wolf",
                        "match": "//.*$"
                    }
                ]
            },

            // `#[…]` is a BOUNDED region — and so is `#![…]`, the file-wide
            // inner attribute (`[gram.attr.index]`, s126). Wolf has no
            // preprocessor, so `#` must never swallow the rest of the line —
            // the trap `clients/facsimile/inventory.md` records from the
            // other side.
            "attributes": {
                "name": "meta.attribute.wolf",
                "begin": "#!?\\[",
                "end": "\\]",
                "beginCaptures": { "0": { "name": "punctuation.definition.attribute.wolf" } },
                "endCaptures": { "0": { "name": "punctuation.definition.attribute.wolf" } },
                "patterns": [
                    { "include": "#strings" },
                    { "include": "#numbers" }
                ]
            },

            // Order is the whole content of this rule. `"""` before `"`, or
            // the opening fence lexes as an empty string followed by a string
            // start; raw before generalized, or `r"` is read as a
            // generalized literal with the prefix `r`.
            "strings": {
                "patterns": [
                    { "include": "#block-string" },
                    { "include": "#raw-string" },
                    { "include": "#generalized-string" },
                    { "include": "#quoted-string" }
                ]
            },

            "block-string": {
                "name": "string.quoted.triple.wolf",
                "begin": "\"\"\"",
                "end": "\"\"\"",
                "beginCaptures": { "0": { "name": "punctuation.definition.string.begin.wolf" } },
                "endCaptures": { "0": { "name": "punctuation.definition.string.end.wolf" } },
                "patterns": [ { "include": "#interpolation" } ]
            },

            // `r#"…"#`, with the fence balanced BY COUNT through a
            // backreference to the opening capture. This is the one place
            // TextMate is strictly more expressive than the Vim syntax file
            // ls04 shipped: `clients/nvim/inventory.md` has to enumerate
            // `r"`, `r#"`, `r##"`, `r###"` and gives up past three, because
            // Vim's regex has no counting construct. `\1` counts.
            "raw-string": {
                "name": "string.quoted.other.raw.wolf",
                "begin": "\\br(#*)\"",
                "end": "\"\\1",
                "beginCaptures": { "0": { "name": "punctuation.definition.string.begin.wolf" } },
                "endCaptures": { "0": { "name": "punctuation.definition.string.end.wolf" } },
                "patterns": [ { "include": "#interpolation" } ]
            },

            // `re"…"` — an identifier FUSED to a string. The prefix is part of
            // the literal, so it colours as one thing; `re` alone would read
            // as a variable. Adjacency is required, which is what keeps
            // `extern "C"` (a keyword, a space, a string) out of this rule.
            "generalized-string": {
                "name": "string.quoted.other.generalized.wolf",
                "begin": "\\b([A-Za-z_][A-Za-z0-9_]*)(\")",
                "end": "\"",
                "beginCaptures": {
                    "1": { "name": "support.function.generalized.wolf" },
                    "2": { "name": "punctuation.definition.string.begin.wolf" }
                },
                "endCaptures": { "0": { "name": "punctuation.definition.string.end.wolf" } },
                "patterns": [ { "include": "#interpolation" } ]
            },

            "quoted-string": {
                "name": "string.quoted.double.wolf",
                "begin": "\"",
                "end": "\"",
                "beginCaptures": { "0": { "name": "punctuation.definition.string.begin.wolf" } },
                "endCaptures": { "0": { "name": "punctuation.definition.string.end.wolf" } },
                "patterns": [ { "include": "#interpolation" } ]
            },

            // EVERY string literal is an f-string (D26/X9), which is why this
            // rule is included from all four forms rather than from the plain
            // one. The doubled-brace escapes are matched FIRST, so `{{` never
            // opens an interpolation.
            "interpolation": {
                "patterns": [
                    {
                        "name": "constant.character.escape.wolf",
                        "match": "\\{\\{|\\}\\}"
                    },
                    {
                        "name": "meta.embedded.expression.wolf",
                        "begin": "\\{",
                        "end": "\\}",
                        "beginCaptures": { "0": { "name": "punctuation.section.interpolation.begin.wolf" } },
                        "endCaptures": { "0": { "name": "punctuation.section.interpolation.end.wolf" } },
                        "patterns": [
                            { "include": "#format-spec" },
                            { "include": "#numbers" },
                            { "include": "#keywords" },
                            { "include": "#types" },
                            { "include": "#operators" }
                        ]
                    }
                ]
            },

            // `FORMAT_SPEC ::= ':' …` — the `:>3` in `{words:>3}`.
            "format-spec": {
                "name": "constant.other.format-spec.wolf",
                "match": ":[^{}\"]*(?=\\})"
            },

            // `[gram.lex.char]` (D58, the 83f83bb pin): one scalar or one
            // escape between single quotes — `'a'`, `'\n'`, `'\x41'`,
            // `'\u{1F43A}'`. The match is CLOSED (both quotes in one regex,
            // no begin/end region) because a lone `'` is a stray byte in
            // wolf, not a string opener — a region rule would swallow the
            // rest of the line the way `#` must not (the facsimile trap).
            "chars": {
                "name": "constant.character.wolf",
                "match": "'([^'\\\\\\r\\n]|\\\\[ntr0\\\\'\"]|\\\\x[0-9A-Fa-f]{2}|\\\\u\\{[0-9A-Fa-f]+\\})'",
                "captures": { "0": { "name": "constant.character.wolf" } }
            },

            // Radix forms before decimal, or `0x1f` lexes as `0` followed by
            // an identifier. Float before decimal for the same reason.
            "numbers": {
                "patterns": [
                    { "name": "constant.numeric.hex.wolf", "match": "\\b0x[0-9A-Fa-f][0-9A-Fa-f_]*\\b" },
                    { "name": "constant.numeric.octal.wolf", "match": "\\b0o[0-7][0-7_]*\\b" },
                    { "name": "constant.numeric.binary.wolf", "match": "\\b0b[01][01_]*\\b" },
                    { "name": "constant.numeric.float.wolf", "match": "\\b[0-9][0-9_]*(\\.[0-9][0-9_]*([eE][+-]?[0-9][0-9_]*)?|[eE][+-]?[0-9][0-9_]*)" },
                    { "name": "constant.numeric.decimal.wolf", "match": "\\b[0-9][0-9_]*\\b" }
                ]
            },

            "keywords": { "patterns": keyword_patterns },

            "types": {
                "name": "support.type.wolf",
                "match": word_alternation(&types)
            },

            "operators": {
                "name": "keyword.operator.wolf",
                "match": operator_alternation
            }
        }
    })
}

/// A grammar that is nothing but `source.wolf`.
///
/// The `runtime! syntax/wolf.vim` of this client: sourcing rather than copying
/// is the whole point, so a keyword added to the derived set does not need a
/// second edit here to appear.
fn including_grammar(scope: &str, name: &str, what: &str) -> Value {
    json!({
        "information_for_contributors": generated_banner(what),
        "name": name,
        "scopeName": scope,
        "patterns": [ { "include": "source.wolf" } ]
    })
}

/// `src/pin.ts`, from `vendor/upstream/PIN`.
fn pin_ts(pin: &str) -> String {
    let value = |key: &str| -> String {
        pin.lines()
            .map(|l| l.split('#').next().unwrap_or("").trim())
            .find_map(|l| {
                let (k, v) = l.split_once('=')?;
                (k.trim() == key).then(|| v.trim().trim_matches('"').to_string())
            })
            .unwrap_or_default()
    };
    format!(
        r#"// GENERATED by `cargo xtask grammar-generate` from vendor/upstream/PIN.
// Do not edit; `cargo xtask grammar-drift` fails on a hand edit.
//
// The wolf-lang build this extension was verified against. `Wolf: Show Version`
// compares a user's `wolf --version` against `version` and reports a mismatch
// WITHOUT calling it unsupported: a supported version RANGE is ls07's to
// define, and this repo's only honest fact today is one exact pin.

export const PIN = {{
	commit: '{commit}',
	version: '{version}',
	servesLsp: {serves_lsp},
}} as const;
"#,
        commit = value("commit"),
        version = value("version"),
        serves_lsp = value("serves_lsp"),
    )
}

// ---------------------------------------------------------------- driver --

/// Render a JSON document the way this repo commits JSON: two-space indent
/// (`.editorconfig`) and a trailing newline.
fn render(value: &Value) -> String {
    let mut text = serde_json::to_string_pretty(value).expect("a generated grammar serializes");
    text.push('\n');
    text
}

/// The four generated files, as `(path, contents)`.
fn artifacts(root: &Path) -> Result<Vec<(PathBuf, String)>, Vec<String>> {
    let vendor = root.join("vendor").join("upstream");
    let ebnf_path = vendor.join("spec").join("grammar.ebnf");
    let ebnf = std::fs::read_to_string(&ebnf_path)
        .map_err(|e| vec![format!("{}: {e}", crate::slash(&ebnf_path))])?;
    let pin_path = vendor.join("PIN");
    let pin = std::fs::read_to_string(&pin_path)
        .map_err(|e| vec![format!("{}: {e}", crate::slash(&pin_path))])?;

    let inv = inventory(&ebnf)?;
    let vscode = root.join("clients").join("vscode");
    let syntaxes = vscode.join("syntaxes");

    Ok(vec![
        (
            syntaxes.join("wolf.tmLanguage.json"),
            render(&wolf_grammar(&inv)),
        ),
        (
            syntaxes.join("wolfi.tmLanguage.json"),
            render(&including_grammar(
                "source.wolfi",
                "Wolf interface",
                "`.wolfi` is lexically wolf; this grammar is `source.wolf` and nothing else.",
            )),
        ),
        (
            syntaxes.join("wolf-pkg.tmLanguage.json"),
            render(&including_grammar(
                "source.wolf-pkg",
                "Wolf manifest",
                "`wolf.pkg`/`wolf.sum` are wolf-literal data; this grammar is `source.wolf`.",
            )),
        ),
        (vscode.join("src").join("pin.ts"), pin_ts(&pin)),
    ])
}

/// `grammar-drift` (check) and `grammar-generate` (write).
pub fn derived(root: &Path, write: bool) -> Vec<String> {
    let mut errors = match artifacts(root) {
        Ok(a) => {
            let mut errors = Vec::new();
            for (path, want) in a {
                let have = std::fs::read_to_string(&path).unwrap_or_default();
                if have == want {
                    eprintln!("vscode: {} is current", crate::slash(&path));
                    continue;
                }
                if write {
                    if let Some(parent) = path.parent() {
                        let _ = std::fs::create_dir_all(parent);
                    }
                    match std::fs::write(&path, &want) {
                        Ok(()) => eprintln!("vscode: wrote {}", crate::slash(&path)),
                        Err(e) => errors.push(format!("{}: {e}", crate::slash(&path))),
                    }
                } else {
                    errors.push(format!(
                        "{} differs from what the pin generates — it is GENERATED, so this is \
                         either a hand edit or a stale pin. Remedy, always one commit: \
                         `cargo xtask grammar-generate`, then commit the result with the pin \
                         bump that caused it.",
                        crate::slash(&path)
                    ));
                }
            }
            errors
        }
        Err(e) => e,
    };
    errors.sort();
    errors.dedup();
    errors
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The pinned grammar, so these tests fail on a pin bump that changes the
    /// language rather than passing against a fixture nobody re-vendors.
    fn pinned_ebnf() -> String {
        let path = crate::repo_root()
            .join("vendor")
            .join("upstream")
            .join("spec")
            .join("grammar.ebnf");
        std::fs::read_to_string(path).expect("the vendored grammar is present")
    }

    #[test]
    fn the_pinned_grammar_classifies_every_word_terminal() {
        // The generator refuses to run on an unclassified word, so this is
        // also the assertion that CONTEXTUAL is exhaustive at the pin.
        let inv = inventory(&pinned_ebnf()).expect("every word terminal is classified");
        assert_eq!(
            inv.keywords.len(),
            50,
            "`reserved_kw` is the spec's own checksum; it carries 50 names at this pin"
        );
    }

    /// The exact trap that made the comment strip necessary.
    #[test]
    fn prose_apostrophes_are_not_mistaken_for_terminals() {
        let ebnf = "reserved_kw ::= 'fn'\n\
                    ret_type ::= type /* `-> !T` parses via type's '!' type */\n";
        let found = terminals(ebnf);
        assert!(
            found.contains("fn"),
            "the real terminal survives: {found:?}"
        );
        assert!(
            !found.iter().any(|t| t.contains("type */") || t == "s "),
            "prose leaked into the terminal set: {found:?}"
        );
    }

    #[test]
    fn operators_are_emitted_longest_first() {
        let inv = inventory(&pinned_ebnf()).unwrap();
        let lengths: Vec<usize> = inv.operators.iter().map(|o| o.chars().count()).collect();
        assert!(
            lengths.windows(2).all(|w| w[0] >= w[1]),
            "a first-match alternation must list `..=` before `..`: {:?}",
            inv.operators
        );
    }

    /// The inverse of the tripwire that guarded the ls02/ls04/ls05 extraction
    /// gap: at f9ee9aa the vendored EBNF renders the precedence climb, so the
    /// thirteen operators the old gap was missing are asserted PRESENT — a
    /// pin where they vanish again is a regression upstream, not a shrug.
    #[test]
    fn the_precedence_climb_operators_stay_in_the_vendored_ebnf() {
        let inv = inventory(&pinned_ebnf()).unwrap();
        for op in [
            "==", "!=", "<", ">", "<=", ">=", "<=>", "&&", "||", "<<", ">>", "/", "&",
        ] {
            assert!(
                inv.operators.iter().any(|o| o == op),
                "`{op}` fell OUT of the vendored EBNF — the precedence climb the f9ee9aa \
                 extraction renders (spec [gram.expr.prec]) has regressed. See \
                 `clients/vscode/inventory.md` §THE OPERATOR GAP for the history."
            );
        }
    }

    #[test]
    fn every_reserved_keyword_reaches_the_emitted_grammar_exactly_once() {
        let inv = inventory(&pinned_ebnf()).unwrap();
        let grammar = wolf_grammar(&inv);
        let patterns = grammar["repository"]["keywords"]["patterns"]
            .as_array()
            .expect("keyword patterns");
        let mut seen: Vec<String> = Vec::new();
        for p in patterns {
            let m = p["match"].as_str().expect("a match pattern");
            let inner = m
                .trim_start_matches("\\b(")
                .trim_end_matches(")\\b")
                .to_string();
            seen.extend(inner.split('|').map(str::to_string));
        }
        seen.sort();
        let mut expected: Vec<String> = inv.keywords.iter().cloned().collect();
        expected.sort();
        assert_eq!(
            seen, expected,
            "the union of the keyword scopes must be exactly `reserved_kw` — the split is \
             cosmetic, the union is the claim"
        );
    }

    /// A keyword this table has never heard of must still reach the editor.
    #[test]
    fn an_unmapped_keyword_lands_in_the_generic_scope_rather_than_vanishing() {
        let inv = Inventory {
            keywords: ["fn", "sync"].iter().map(|s| (*s).to_string()).collect(),
            operators: vec!["+".to_string()],
        };
        let grammar = wolf_grammar(&inv);
        let rendered = render(&grammar);
        assert!(
            rendered.contains("keyword.other.wolf"),
            "an unmapped keyword needs a home"
        );
        assert!(rendered.contains("sync"), "…and must appear in it");
    }

    #[test]
    fn generation_is_deterministic() {
        let inv = inventory(&pinned_ebnf()).unwrap();
        assert_eq!(render(&wolf_grammar(&inv)), render(&wolf_grammar(&inv)));
    }
}
